name: CI/CD workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6

      - name: lint
        uses: golangci/golangci-lint-action@v9

      - name: unit tests
        run: go test -v ./...

      - name: build image
        run: docker build -t release-notifier:latest
